language: cpp
compiler: gcc
os: linux
before_install:
    - pip install -U pytest --user
    - sudo apt-get install libboost-dev

script:
    - cmake .
    - make clean
    - make
    - sudo make install

    - cd tests
    - pytest -v
    - cd -
